# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offspring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('tag', models.IntegerField()),
                ('date_of_birth', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspring', to='herd.Herd')),
            ],
        ),
    ]
