# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0002_offspring'),
    ]

    operations = [
        migrations.AddField(
            model_name='offspring',
            name='sire',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sire', to='herd.Herd'),
        ),
    ]
